### ISSUE TITLE
set institution and external urls in the faculty profiles

### ISSUE THREAD

**Issue by omazapa** [colav-playground/hunabku_impactu#11]
similar to #9 and #8 
the website is only displaying the name of the faculty but not the university it belongs, and maybe additional information
would be good
@restrepo something else is needed?

![image](https://github.com/colav-playground/hunabku_impactu/assets/275148/5a538c71-539a-4cc5-ab3b-8ff4a9bfeae0)

**Comment by Simon3640** [comment]
pipeline for add extra information https://github.com/colav-playground/hunabku_impactu/commit/6a2cf1306f06125a27364ff391079979fd6557c9
