### ISSUE TITLE
set institution and external urls in the group profiles

### ISSUE THREAD

**Issue by omazapa** [colav-playground/hunabku_impactu#8]
the website is only displaying the name of the group but not the university, faculty and department it belongs, and maybe additional information would be good  
@restrepo something else is needed?
![image](https://github.com/colav-playground/hunabku_impactu/assets/275148/4cd2adf6-9c4b-4f7d-b015-d36696bac8f5)

**Comment by Simon3640** [comment]
pipeline for add extra information https://github.com/colav-playground/hunabku_impactu/commit/6a2cf1306f06125a27364ff391079979fd6557c9
