### ISSUE TITLE
set institution and external urls in the department profiles

### ISSUE THREAD

**Issue by omazapa** [colav-playground/hunabku_impactu#9]
this is similar to issue #8 
the website is only displaying the name of the departmet but not the university it belongs, and maybe additional information
would be good
@restrepo something else is needed?

![image](https://github.com/colav-playground/hunabku_impactu/assets/275148/20e453cb-a060-4b8a-93cd-9ae88bb3f22d)

**Comment by restrepo** [comment]
Departamento must include Facultada.  
Facultad profile must include the name of the University
See also https://github.com/colav-playground/hunabku_impactu/issues/8

**Comment by Simon3640** [comment]
pipeline for add extra information https://github.com/colav-playground/hunabku_impactu/commit/6a2cf1306f06125a27364ff391079979fd6557c9
